# This workflow will build a package (jar, sources, javadoc) & install into the local directory.
# This workflow triggers on pull request to main branch. If the build fails, we should not merge
# the PR.

name: Maven Build on Pull Request

on:
   pull_request:
      branches:
         - 'main'

jobs:
  build-on-pull-request:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build & install with Maven # mvn install will run preceeding goals - test, compile, pacakge, etc
      run: |
         chmod -v a+x $GITHUB_WORKSPACE/mvnw # Allow execute permissions on mvnw script for all users
         $GITHUB_WORKSPACE/mvnw -B install --file pom.xml