# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build & Publish

on:
  push:
    branches:    
      - 'main'

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: test123
      run: mvn --version
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: test1234
      run: mvn --version

    - name: Build & deploy with Maven # mvn deploy will run preceeding goals - test, compile, pacakge, etc
      run: mvn -B deploy --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}